[package]
name = "full-cli-rs"
version = "0.0.1"
authors = ["Samuel Marks <@SamuelMarks>"]
edition = "2018"

[dependencies]
docopt = "1.1"
env_logger = "0.6.2"
failure = "0.1.5"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
libconsensus = {git = "https://github.com/Fantom-foundation/libconsensus"}
libcli = {git = "https://github.com/Fantom-foundation/libcli"}
log = "0.4.8"
ring = "0.13.4"
serde = "1.0.98"
serde_derive = "1.0.98"
tokio = "0.2.0-alpha.1"
toml = "0.5"
vm = { git = "https://github.com/Fantom-foundation/librevm-rs" }
libtransport = { git = "https://github.com/Fantom-foundation/libtransport.git" }
libtransport-tcp = { git = "https://github.com/Fantom-foundation/libtransport-tcp.git"}
libvm = { git = "https://github.com/Fantom-foundation/libvm.git" }