[package]
name = "full-cli-rs"
version = "0.0.1"
authors = ["Samuel Marks <@SamuelMarks>"]
edition = "2018"

[dependencies]
docopt = "1.1"
failure = "0.1.5"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
libconsensus = {git = "https://github.com/Fantom-foundation/libconsensus"}
libconsensus-lachesis-rs = {git = "https://github.com/Fantom-foundation/libconsensus-lachesis-rs"}
libcli = {git = "https://github.com/Fantom-foundation/libcli"}
ring = "0.13.4"
serde = "1.0.98"
serde_derive = "1.0.98"
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.1"
tokio = "0.2.0-alpha.1"
toml = "0.5"
vm = {git = "https://github.com/Fantom-foundation/librevm-rs"}
