[package]
name = "full-cli-rs"
version = "0.0.1"
authors = ["Samuel Marks <@SamuelMarks>"]
edition = "2018"

[dependencies]
docopt = "1.1.0"
env_logger = "0.7.0"
failure = "0.1.5"
libconsensus = { git = "https://github.com/Fantom-foundation/libconsensus" }
libconsensus-lachesis-rs = { git = "https://github.com/Fantom-foundation/libconsensus-lachesis-rs" }
libcli = { git = "https://github.com/Fantom-foundation/libcli" }
log = "0.4.8"
ring = "0.13.5"
serde = "1.0.101"
serde_derive = "1.0.101"
tokio = "0.1.22"
toml = "0.5.3"
vm = { git = "https://github.com/Fantom-foundation/librevm-rs" }
