[package]
name = "full-cli-rs"
version = "0.0.1"
authors = ["Samuel Marks <@SamuelMarks>"]
edition = "2018"

[dependencies]
structopt = { version = "0.2", default-features = false }
libconsensus = {git = "https://github.com/Fantom-foundation/libconsensus"}
libconsensus-lachesis-rs = {git = "https://github.com/Fantom-foundation/libconsensus-lachesis-rs"}
libcli = {git = "https://github.com/Fantom-foundation/libcli"}